trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - release*
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - LICENSE

jobs:
  - job: Test
    pool:
      vmImage: 'Ubuntu-20.04'

    steps:
      - task: GoTool@0
        inputs:
          version: '1.18'
        displayName: 'Install Golang'

      - script: |
          set -e
          make lint
        displayName: 'Lint Source'

      - script: |
          set -e
          make test
        displayName: 'Unit Test'

      - script: |
          set -e
          test/bootstrap.bash
        displayName: 'Bootstrap tests'

      - script: |
          set -e
          test/setup.bash
        displayName: 'Setup test environment'

      - script: |
          set -e
          test/run.bash
        displayName: 'Run tests'

      - script: |
          test/teardown.bash
        displayName: 'Teardown test environment'
