trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - release*
  paths:
    exclude:
      - README.md

pr: none

variables:
  GOROOT: '/usr/local/go1.12' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  GOBIN:  '$(GOPATH)/bin' # Go binaries path

jobs:
  - job: Test
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - script: |
          mkdir -p '$(GOBIN)'
          mkdir -p '$(GOPATH)/pkg'
        displayName: 'Set up the Go workspace'

      - task: GoTool@0
        inputs:
          version: '1.12.1'
          goPath: $(GOPATH)
          goBin: $(GOBIN)
        displayName: 'Install Golang'

      - script: |
          ./script/check_fmt.sh
        displayName: 'Check Source Format'

      - script: |
          script/bootstrap.sh
        displayName: 'Bootstrap'

      - script: |
          make test
        displayName: 'Run Unit Tests'
